# Generated by Django 5.2 on 2025-04-28 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('faculty', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('pull_over', 'Turnikdan göwräňi aşyrmak'), ('pull_up', 'Turnikdan çekinmek'), ('run', 'Ylgaw')], max_length=20)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_results', to='students.student')),
            ],
        ),
    ]
