# Generated by Django 5.2 on 2025-04-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseresult',
            name='exercise_type',
            field=models.CharField(choices=[('pull_over', 'Turnikdan göwräňi aşyrmak'), ('pull_up', 'Turnikdan çekmek'), ('run', 'Ylgaw')], max_length=20),
        ),
    ]
