# Generated by Django 5.2 on 2025-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_exerciseresult_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
